"""change project.image to bool

Revision ID: 35f3f468dd5e
Revises: 5cdcb2f9c272
Create Date: 2023-11-22 18:43:40.458271

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "35f3f468dd5e"
down_revision: Union[str, None] = "5cdcb2f9c272"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project",
        "image",
        existing_type=sa.VARCHAR(),
        type_=sa.Boolean(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project",
        "image",
        existing_type=sa.Boolean(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
