"""add project link

Revision ID: 5cdcb2f9c272
Revises: 45c6b4c506ae
Create Date: 2023-11-21 19:25:32.205061

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5cdcb2f9c272"
down_revision: Union[str, None] = "45c6b4c506ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("link", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "link")
    # ### end Alembic commands ###
